services:
  - type: web
    name: pos-system-backend
    env: node
    region: oregon
    plan: free
    buildCommand: cd server && rm -rf node_modules && npm install --production=false && npm rebuild sqlite3
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://your-frontend-domain.vercel.app
    healthCheckPath: /api/health
